version = "1.1";

id = "1DAdcKgOvcPJlk4sZrLOVB1KAI2Y_wXyV";

games = {
    "2048": "2048",
    "Among Us": "among-us",
    "Animal Stacking": "animal-stacking",
    "Appel": "appel",
    "Arena": "arena",
    "Asteroids": "asteroids",
    "Ball Blast": "ball-blast",
    "Black Jack": "black-jack",
    "Bubbles 200": "bubbles-200",
    "Bullet Train II": "bullet-train-ii",
    "Connect 4": "connect-4",
    "Drifting Sim 6": "drifting-sim-6",
    "Flappy Bird": "flappy-bird",
    "Getting Over It": "getting-over-it",
    "Level EATEN!": "level-eaten",
    "Low Res Lines": "low-res-lines",
    "Mage Royale": "mage-royale",
    "Minecraft MMO": "minecraft-mmo",
    "Mini Golf": "mini-golf",
    "Murder Mysyery": "murder-mystery",
    "Mystic Valley": "mystic-valley",
    "Paper.io": "paper-io",
    "Paper Minecraft": "paper-minecraft",
    "PHANTOM": "phantom",
    "Pokemon Clicker": "pokemon-clicker",
    "Pong": "pong",
    "Prop Hunt": "prop-hunt",
    "Retro Racer": "retro-racer",
    "Scratcharia": "scratcharia",
    "Sega Virtual Racing": "sega-virtual-racing",
    "Slash Knight": "slash-knight",
    "Slime Smash Ultimate": "slime-smash-ultimate",
    "Slither.io": "slither-io",
    "Stack 2D": "stack-2d",
    "Super Mario Kart": "super-mario-kart",
    "Submersible": "submersible",
    "Terraria": "terraria",
    "Tetris": "tetris",
    "Tower Of Scratch": "tower-of-scratch",
    "Uno": "uno",
    "Wolfenstein 3D": "wolfenstein-3d"
}